name: Design Changes Workflow

on:
  workflow_dispatch:
    inputs:
      description:
        description: 'What are we updating (eg. update button destructive color)?'
        default: ''
        required: true
      jira:
        description: 'What is the related Jira (eg. SW-1234)?'
        default: ''
        required: true
      email:
        description: 'Your terraformation email'
        default: ''
        required: true

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Sanitize user input
        run: |
          echo JIRA=$(echo ${{ github.event.inputs.jira }} | tr '"' '\\\"' | tr '$' '\$') >> $GITHUB_ENV 
          echo DESCRIPTION=$(${{ github.event.inputs.description }} | tr '"' '\\\"' | tr '$' '\$') >> $GITHUB_ENV 
          echo EMAIL=$(echo ${{ github.event.inputs.email }} | tr '"' '\\\"' | tr '$' '\$') >> $GITHUB_ENV 

      - name: Create branch
        run: git checkout -b $(echo design-workflow-${{ github.actor }}-${{ env.JIRA }}-$(date +%y-%m-%d-%s) | tr ' ' -)

      - name: Install Dependencies
        run: yarn install --network-timeout 100000

      - name: Build dictionary 
        run: yarn build-dictionary

      - name: Bump package patch version
        run: yarn bump patch

      - name: Config user
        run: |
          git config --global user.email ${{ env.EMAIL }}
          git config --global user.name ${{ github.actor }}

      - name: Commit changes
        run: |
          git add -A
          git commit -m "${{ env.DESCRIPTION }}"

      - name: Push changes
        run: git push -u origin `git branch --show-current`

      - name: Create PR
        run: gh pr create --title "${{ env.JIRA }} - ${{ env.DESCRIPTION }}" --body "${{ env.DESCRIPTION }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
