name: Design changes workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Describe changes in very few words'
        default: ''
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 automate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: create branch
        run: git checkout -b `echo ${{ github.event.inputs.name }} | sed "s/ /-/g"`

      - name: download design tokens
        run: |
          echo yarn build-dictionary
          echo 'hello world' > design.txt

      - name: commit changes
        run: |
          git add -A
          git commit -m "${{ github.event.inputs.name }}"
          git push
          gh pr create --fill
